### ISSUE TITLE
Тестирование эвристик

### ISSUE THREAD

**Issue by BruchesLena** [OnPositive/text-analisis#8]
1. Проверять конфликт только для разных частей речи;
2. Выводить все конфликты, для каждого конфликта вывести предложение, в котором он встретился, или слово до и слово после;
3. Для правильно разрешённого конфликта выводить номер набора правил и номер правила, с помощью которого он разрешился;
4. Для неправильно разрешённого конфликта выводить номера конфликтующих правил; если правила не нашлось, то выводить "Нет правила";
5. Выводить точность разрешённых конфликтов (количество правильно разрешённых конфликтов / количество всех конфликтов).

**Comment by 32kda** [comment]
Сравнение исправлено, данные требования учтены
